### ISSUE TITLE
Error while creating stardict for PGN

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/stardict-sanskrit#52]
Error log is as below.

I tried with other dictionaries too. 
Tried going down a step to sa-head/en-entries.
Didn't help.

There are 8-10 dictionaries all converted to babylon. This hitch keeps me from posting them.

```
dhaval@dhaval-ThinkCentre-M73:~/stardict-sanskrit/sa-head$ make DICTS='Personal-and-Geographical-Names-in-the-Gupta-Inscriptions'
make -C sa-entries all
make[1]: Entering directory '/home/dhaval/stardict-sanskrit/sa-head/sa-entries'
bash ../../bin/babylon_add_optitrans.sh DICTS=Personal-and-Geographical-Names-in-the-Gupta-Inscriptions
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/dhaval/sanskritnlpjava/out/sanskritnlpjava.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dhaval/sanskritnlpjava/out/stardict-sanskrit.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dhaval/sanskritnlpjava/out/subhAShitadb.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
14:10:16 stardict_sanskrit.batchProcessor$ 120 --- =======================Adding optitrans headwords, making final babylon file.
14:10:16 stardict_sanskrit.batchProcessor$ 110 --- file_pattern: Personal-and-Geographical-Names-in-the-Gupta-Inscriptions
14:10:16 stardict_sanskrit.batchProcessor$ 113 --- Got 0 directories
14:10:16 stardict_sanskrit.batchProcessor$ 123 --- Got 0 babylon files
14:10:16 stardict_sanskrit.batchProcessor$ 129 --- Got 0 babylon files
bash ../../bin/tsv_to_stardict.sh DICTS=Personal-and-Geographical-Names-in-the-Gupta-Inscriptions
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/dhaval/sanskritnlpjava/out/sanskritnlpjava.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dhaval/sanskritnlpjava/out/stardict-sanskrit.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dhaval/sanskritnlpjava/out/subhAShitadb.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
14:10:17 stardict_sanskrit.batchProcessor$ 145 --- =======================makeStardict
14:10:17 stardict_sanskrit.batchProcessor$ 110 --- file_pattern: Personal-and-Geographical-Names-in-the-Gupta-Inscriptions
14:10:17 stardict_sanskrit.batchProcessor$ 113 --- Got 0 directories
14:10:17 stardict_sanskrit.batchProcessor$ 148 --- Got 0 babylon_final files
14:10:17 stardict_sanskrit.batchProcessor$ 149 --- Got 0  dicts without babylon_final files but with babylon file.
bash ../../bin/make_tarballs.sh https://github.com/sanskrit-coders/stardict-sanskrit/raw/master/sa-head/sa-entries DICTS=Personal-and-Geographical-Names-in-the-Gupta-Inscriptions
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/dhaval/sanskritnlpjava/out/sanskritnlpjava.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dhaval/sanskritnlpjava/out/stardict-sanskrit.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dhaval/sanskritnlpjava/out/subhAShitadb.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
14:10:18 stardict_sanskrit.batchProcessor$ 169 --- =======================makeTars
14:10:18 stardict_sanskrit.batchProcessor$ 110 --- file_pattern: Personal-and-Geographical-Names-in-the-Gupta-Inscriptions
14:10:18 stardict_sanskrit.batchProcessor$ 113 --- Got 0 directories
14:10:18 stardict_sanskrit.batchProcessor$ 172 --- Got 0 tar files
14:10:18 stardict_sanskrit.batchProcessor$ 173 --- Got 0  dicts without tarFile files but with ifo file.
14:10:18 stardict_sanskrit.batchProcessor$ 181 --- got 0 dictionaries which need to be updated.
make[1]: Leaving directory '/home/dhaval/stardict-sanskrit/sa-head/sa-entries'
make -C en-entries all
make[1]: Entering directory '/home/dhaval/stardict-sanskrit/sa-head/en-entries'
bash ../../bin/babylon_add_optitrans.sh DICTS=Personal-and-Geographical-Names-in-the-Gupta-Inscriptions
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/dhaval/sanskritnlpjava/out/sanskritnlpjava.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dhaval/sanskritnlpjava/out/stardict-sanskrit.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dhaval/sanskritnlpjava/out/subhAShitadb.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
14:10:18 stardict_sanskrit.batchProcessor$ 120 --- =======================Adding optitrans headwords, making final babylon file.
14:10:18 stardict_sanskrit.batchProcessor$ 110 --- file_pattern: Personal-and-Geographical-Names-in-the-Gupta-Inscriptions
14:10:18 stardict_sanskrit.batchProcessor$ 113 --- Got 1 directories
14:10:18 stardict_sanskrit.Dictionary 34 --- Personal-and-Geographical-Names-in-the-Gupta-Inscriptions with Some(/home/dhaval/stardict-sanskrit/sa-head/en-entries/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions.babylon) babylon, None babylonFinal, None ifo, None tar 
14:10:18 stardict_sanskrit.batchProcessor$ 123 --- Got 1 babylon files
14:10:18 stardict_sanskrit.batchProcessor$ 129 --- Got 1 babylon files
14:10:18 stardict_sanskrit.batchProcessor$ 137 --- Adding headwords to: /home/dhaval/stardict-sanskrit/sa-head/en-entries/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions.babylon
Processing /home/dhaval/stardict-sanskrit/sa-head/en-entries/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions.babylon
Will produce /home/dhaval/stardict-sanskrit/sa-head/en-entries/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions.babylon_final
Produced /home/dhaval/stardict-sanskrit/sa-head/en-entries/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions.babylon_final
bash ../../bin/tsv_to_stardict.sh DICTS=Personal-and-Geographical-Names-in-the-Gupta-Inscriptions
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/dhaval/sanskritnlpjava/out/sanskritnlpjava.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dhaval/sanskritnlpjava/out/stardict-sanskrit.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/dhaval/sanskritnlpjava/out/subhAShitadb.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
14:10:20 stardict_sanskrit.batchProcessor$ 145 --- =======================makeStardict
14:10:20 stardict_sanskrit.batchProcessor$ 110 --- file_pattern: Personal-and-Geographical-Names-in-the-Gupta-Inscriptions
14:10:20 stardict_sanskrit.batchProcessor$ 113 --- Got 1 directories
14:10:20 stardict_sanskrit.Dictionary 34 --- Personal-and-Geographical-Names-in-the-Gupta-Inscriptions with Some(/home/dhaval/stardict-sanskrit/sa-head/en-entries/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions.babylon) babylon, Some(/home/dhaval/stardict-sanskrit/sa-head/en-entries/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions.babylon_final) babylonFinal, None ifo, None tar 
14:10:20 stardict_sanskrit.batchProcessor$ 148 --- Got 1 babylon_final files
14:10:20 stardict_sanskrit.batchProcessor$ 149 --- Got 0  dicts without babylon_final files but with babylon file.
14:10:20 stardict_sanskrit.Dictionary 68 --- Making stardict from: /home/dhaval/stardict-sanskrit/sa-head/en-entries/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions/Personal-and-Geographical-Names-in-the-Gupta-Inscriptions.babylon_final
** Message: Over.
** Message: wordcount: 484.
** Message: synwordcount: 484.
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:347)
	at scala.None$.get(Option.scala:345)
	at stardict_sanskrit.Dictionary.makeStardictFromBabylonFile(Dictionary.scala:71)
	at stardict_sanskrit.batchProcessor$$anonfun$makeStardict$4.apply(Dictionary.scala:155)
	at stardict_sanskrit.batchProcessor$$anonfun$makeStardict$4.apply(Dictionary.scala:155)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at stardict_sanskrit.batchProcessor$.makeStardict(Dictionary.scala:155)
	at Main$$anon$1.<init>(scalacmd5461286050633432051.scala:1)
	at Main$.main(scalacmd5461286050633432051.scala:1)
	at Main.main(scalacmd5461286050633432051.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
	at scala.tools.nsc.ScriptRunner.scala$tools$nsc$ScriptRunner$$runCompiled(ScriptRunner.scala:175)
	at scala.tools.nsc.ScriptRunner$$anonfun$runCommand$1.apply(ScriptRunner.scala:222)
	at scala.tools.nsc.ScriptRunner$$anonfun$runCommand$1.apply(ScriptRunner.scala:222)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1$$anonfun$apply$mcZ$sp$1.apply(ScriptRunner.scala:161)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply$mcZ$sp(ScriptRunner.scala:161)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:129)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:129)
	at scala.tools.nsc.util.package$.trackingThreads(package.scala:43)
	at scala.tools.nsc.util.package$.waitingForThreads(package.scala:27)
	at scala.tools.nsc.ScriptRunner.withCompiledScript(ScriptRunner.scala:128)
	at scala.tools.nsc.ScriptRunner.runCommand(ScriptRunner.scala:222)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:85)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
makefile:15: recipe for target 'stardict' failed
make[1]: *** [stardict] Error 1
make[1]: Leaving directory '/home/dhaval/stardict-sanskrit/sa-head/en-entries'
makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by vvasuki** [comment]
Fixed now. Please pull sanskritnlpjava repo etc.. as described in README and you're set.
