### ISSUE TITLE
STC errors

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-coders/stardict-sanskrit#62]
Stchoupak-Sanscrit-French dictionary - tar didn't get compiled properly. Process aborted.

```
07:19:23 stardict_sanskrit.batchProcessor$ 123 --- =======================Adding optitrans headwords, making final babylon file.
07:19:23 stardict_sanskrit.batchProcessor$ 113 --- file_pattern: Stchoupak-Sanscrit-French
07:19:23 stardict_sanskrit.batchProcessor$ 116 --- Got 1 directories
07:19:23 stardict_sanskrit.Dictionary 34 --- Stchoupak-Sanscrit-French with Some(/home/dhaval/stardict-sanskrit/sa-head/other-entries/Stchoupak-Sanscrit-French/Stchoupak-Sanscrit-French.babylon) babylon, None babylonFinal, None ifo, None tar 
07:19:23 stardict_sanskrit.batchProcessor$ 126 --- Got 1 babylon files
07:19:23 stardict_sanskrit.batchProcessor$ 132 --- Got 1 babylon files
07:19:23 stardict_sanskrit.batchProcessor$ 140 --- Adding headwords to: /home/dhaval/stardict-sanskrit/sa-head/other-entries/Stchoupak-Sanscrit-French/Stchoupak-Sanscrit-French.babylon
Processing /home/dhaval/stardict-sanskrit/sa-head/other-entries/Stchoupak-Sanscrit-French/Stchoupak-Sanscrit-French.babylon
Will produce /home/dhaval/stardict-sanskrit/sa-head/other-entries/Stchoupak-Sanscrit-French/Stchoupak-Sanscrit-French.babylon_final
java.nio.charset.MalformedInputException: Input length = 2
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:72)
	at scala.collection.Iterator$$anon$21.hasNext(Iterator.scala:693)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
	at sanskritnlp.dictionary.babylonTools$.addTransliteratedHeadwords(babylonTools.scala:51)
	at stardict_sanskrit.batchProcessor$$anonfun$addOptitrans$3.apply(Dictionary.scala:141)
	at stardict_sanskrit.batchProcessor$$anonfun$addOptitrans$3.apply(Dictionary.scala:136)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at stardict_sanskrit.batchProcessor$.addOptitrans(Dictionary.scala:136)
	at Main$$anon$1.<init>(scalacmd561729431942564847.scala:1)
	at Main$.main(scalacmd561729431942564847.scala:1)
	at Main.main(scalacmd561729431942564847.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.reflect.internal.util.ScalaClassLoader$$anonfun$run$1.apply(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:101)
	at scala.reflect.internal.util.ScalaClassLoader$class.run(ScalaClassLoader.scala:70)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:101)
	at scala.tools.nsc.CommonRunner$class.run(ObjectRunner.scala:22)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:39)
	at scala.tools.nsc.CommonRunner$class.runAndCatch(ObjectRunner.scala:29)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:39)
	at scala.tools.nsc.ScriptRunner.scala$tools$nsc$ScriptRunner$$runCompiled(ScriptRunner.scala:175)
	at scala.tools.nsc.ScriptRunner$$anonfun$runCommand$1.apply(ScriptRunner.scala:222)
	at scala.tools.nsc.ScriptRunner$$anonfun$runCommand$1.apply(ScriptRunner.scala:222)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1$$anonfun$apply$mcZ$sp$1.apply(ScriptRunner.scala:161)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply$mcZ$sp(ScriptRunner.scala:161)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:129)
	at scala.tools.nsc.ScriptRunner$$anonfun$withCompiledScript$1.apply(ScriptRunner.scala:129)
	at scala.tools.nsc.util.package$.trackingThreads(package.scala:43)
	at scala.tools.nsc.util.package$.waitingForThreads(package.scala:27)
	at scala.tools.nsc.ScriptRunner.withCompiledScript(ScriptRunner.scala:128)
	at scala.tools.nsc.ScriptRunner.runCommand(ScriptRunner.scala:222)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:85)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:98)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
makefile:12: recipe for target 'final_babylon' failed
make[1]: *** [final_babylon] Error 1
make[1]: Leaving directory '/home/dhaval/stardict-sanskrit/sa-head/other-entries'
makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by drdhaval2785** [comment]
It was related to the babylon process stopping in between.
Now regenerated.
